### ISSUE TITLE
emit event must be in the update block

### ISSUE THREAD

**Issue by markusvoelter** [ethereum/langlab#6]
@pirapira  emit Incremented(newData) should be in the `update` field.  Events modify the substate, which affects the blockhash.

**Comment by chriseth** [comment]
I'm not 100% sure this has to be the case. While events cannot be emitted in a `STATIC_CALL` context, they are not something that changes state like storage writes do.

**Comment by pirapira** [comment]
I see. The program cannot access the registered events, so firing an event can never break an invariant.

**Comment by markusvoelter** [comment]
Ok, so I close this one :-)
